pipeline {
	agent any
	stages {
		stage('CD stage') {
			steps {
				cd ChatApp
			}
		}
		
		stage('Clean stage') {
			steps {
				withMaven(maven: 'maven_3_6_1') {
					bat 'mvn clean'
				}
			}
		}
		
		stage('Compile stage') {
			steps {
				withMaven(maven: 'maven_3_6_1') {
					bat 'mvn compile'
				}
			}
		}
		
		stage('Install stage') {
			steps {
				withMaven(maven: 'maven_3_6_1') {
					bat 'mvn install'
				}
			}
		}
		
	}
}
